=== GreySux/hud-db/utils/hud-data.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "HUD Data",
  "description": "Data about a HUD",
  "type": "object",
  "required": ["name", "author", "repo", "hash", "resources"],
  "properties": {
    "name": {
      "description": "Display name of your HUD",
      "type": "string",
      "examples": ["My HUD"]
    },
    "author": {
      "description": "Display name of you, the active developer of the HUD (however, outdated HUD maintenance may not count as authoring in some cases)",
      "type": "string",
      "examples": ["Cool person"]
    },
    "contributors": {
      "description": "Display names of anyone you would like to credit for the creation/development of the HUD. Not to be used for general credits, but major and direct contributors",
      "type": "array",
      "items": {
        "type": "string"
      },
      "examples": ["Original creator, Previous maintainer"]
    },
    "releaseDate": {
      "description": "Initial release date of the HUD, YYYY-MM-DD",
      "type": "string",
      "examples": ["2009-12-31"]
    },
    "social": {
      "description": "Links to your social media profiles",
      "type": "object",
      "properties": {
        "support": {
          "description": "A link people can use to support you financially",
          "type": "string",
          "examples": ["https://ko-fi.com/super-duper-person"]
        },
        "issues": {
          "description": "An extra link where users can get help/report issues. If not present, will use GitHub Issues.",
          "type": "string"
        },
        "steam_profile": {
          "description": "Your SteamID64",
          "type": "string",
          "examples": ["76561191234567890"]
        },
        "steam_group": {
          "description": "Your Steam group vanity ID (used for custom URLs)",
          "type": "string",
          "examples": ["valve"]
        },
        "twitter": {
          "description": "Your Twitter handle",
          "type": "string",
          "examples": ["CoolPerson12812381841823812"]
        },
        "discord": {
          "description": "Your Discord server invite code, not the full URL, or your Discord in the format username#0",
          "type": "string",
          "examples": ["vanity-or-invite"]
        },
        "youtube": {
          "description": "Your YouTube channel (either /channel/id URL, @username or channel name)",
          "type": "string",
          "examples": ["@TheCoolPerson"]
        },
        "twitch": {
          "description": "Your Twitch channel name",
          "type": "string",
          "examples": ["CoolPersonStreamer"]
        },
        "album": {
          "description": "Link to some Imgur album or other to provide more images",
          "type": "string",
          "examples": ["https://imgur.com/a/fajsf"]
        }
      }
    },
    "flags": {
      "description": "A list of boolean flags whose presence indicates the existence of a feature of some kind",
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "fonts",
          "menus",
          "scoreboards",
          "crosshairs",
          "minmode",
          "streamer-mode",
          "materials",
          "customization"
        ]
      },
      "uniqueItems": true
    },
    "traits": {
      "description": "Optional structured mapping of values",
      "type": "object",
      "properties": {
        "os": {
          "description": "What operating systems does the HUD support",
          "type": "array",
          "items": {
            "type": "string",
            "enum": ["windows", "mac", "linux"]
          },
          "uniqueItems": true
        },
        "gamemode": {
          "description": "What gamemodes does the HUD customize for",
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "tournament",
              "comp",
              "arena",
              "ad",
              "ctf",
              "cp",
              "halloween",
              "koth",
              "mannpower",
              "mvm",
              "pass",
              "pl",
              "plr",
              "pd",
              "rd",
              "sd",
              "tc"
            ]
          },
          "uniqueItems": true
        },
        "res": {
          "description": "What aspect ratios does the HUD support",
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "1/1",
              "4/3",
              "5/4",
              "16/10",
              "16/9",
              "17/9",
              "21/9",
              "32/9"
            ]
          },
          "uniqueItems": true
        },
        "position": {
          "description": "What position is the ammo/health in the HUD (multiple customization options can be available)",
          "type": "array",
          "items": {
            "type": "string",
            "enum": ["center", "corners", "default"]
          },
          "uniqueItems": true
        },
        "lang": {
          "description": "What languages does the HUD support (if it has custom language files)",
          "type": "array",
          "items": {
            "type": "string"
          },
          "uniqueItems": true,
          "examples": ["en"]
        }
      }
    },
    "tags": {
      "description": "A list of words associated with the HUD for discovery. Be general. First tag is considered primary and used as a category. There is no list of valid tags, but they are subject to review for usefulness/'spamminess'.",
      "type": "array",
      "items": {
        "type": "string"
      },
      "examples": ["minimal, monochrome"]
    },
    "repo": {
      "description": "GitHub repo web URL",
      "type": "string",
      "examples": ["https://github.com/cool-person/myhud"]
    },
    "hash": {
      "description": "Git commit hash of your current version (PR an update to this each time your HUD updates, and we will approve it)",
      "type": "string",
      "examples": ["84c64d403a650b3ae4793c9d32e01b3383445740"]
    },
    "prerelease": {
      "description": "If this is a prerelease/WIP HUD",
      "type": "boolean"
    },
    "verified": {
      "description": "For internal use only to enable some functionality. Do not set this yourself.",
      "type": "boolean"
    },
    "parent": {
      "description": "If this HUD is a slight edit of another, put its ID here. This will group the HUDs together.",
      "type": "string",
      "examples": ["their-hud"]
    },
    "resources": {
      "description": "A list of image names/YouTube videos. Images are automatically converted to webp, do not use extensions for uploaded images. First resource is required, must be an image and is used as the display banner. Resources also support youtu.be links for video embeds.",
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1,
      "maxItems": 15,
      "uniqueItems": true,
      "examples": ["myhud-banner, cool-image-1, https://youtu.be/21asadf"]
    }
  }
}

=== GreySux/hud-db/hud-data/m0re-hypnotize.json
{
  "name": "m0re Hypnotize",
  "author": "Hypnotize",
  "social": {
    "steam_profile": "76561198058754493",
    "album": "http://imgur.com/a/2gckG"
  },
  "flags": [
    "fonts",
    "menus",
    "scoreboards",
    "crosshairs",
    "minmode",
    "materials",
    "customization"
  ],
  "traits": {
    "os": [
      "windows",
      "linux"
    ],
    "gamemode": [
      "tournament",
      "comp",
      "arena",
      "ad",
      "ctf",
      "cp",
      "halloween",
      "koth",
      "mannpower",
      "mvm",
      "pass",
      "pl",
      "plr",
      "pd",
      "rd",
      "sd",
      "tc"
    ],
    "res": [
      "4/3",
      "5/4",
      "16/9",
      "16/10"
    ],
    "position": [
      "center"
    ],
    "lang": [
      "en"
    ]
  },
  "repo": "https://github.com/Hypnootize/Hypnotize-m0rehud",
  "hash": "0809d6196484f6004bb813768ac9d86326b4af44",
  "parent": "m0rehud",
  "resources": [
    "m0rehypnotize-banner",
    "m0rehypnotize-menu",
    "m0rehypnotize-loadout",
    "m0rehypnotize-backpack",
    "m0rehypnotize-classselection",
    "m0rehypnotize-buff",
    "m0rehypnotize-hurt",
    "m0rehypnotize-minmode",
    "m0rehypnotize-engineer",
    "m0rehypnotize-scoreboard",
    "m0rehypnotize-spectator"
  ]
}

=== GreySux/hud-db/hud-data/darhud.json
{
  "name": "DarHUD",
  "author": "DarSitam",
  "contributors": [
    "DarSitam"
  ],
  "releaseDate": "2023-08-17",
  "flags": [
    "scoreboards",
    "minmode",
    "materials",
    "customization"
  ],
  "tags": [
    "modern"
  ],
  "repo": "https://github.com/DarSitam/DarHud",
  "hash": "e77290e80982946314b1627ce69759ea30155b9f",
  "prerelease": false,
  "resources": [
    "darhud-logo"
  ],
  "social": {
    "steam_profile": "76561198148464161",
    "twitter": "DarSitam",
    "discord": "https://discord.gg/txn4CxyVmp",
    "youtube": "@DarSitam",
    "twitch": "DarSitam",
    "album": "https://imgur.com/a/pTE0V2X"
  },
  "traits": {
    "os": [
      "windows"
    ],
    "gamemode": [
      "tournament",
      "arena",
      "ad",
      "ctf",
      "cp",
      "halloween",
      "koth",
      "mannpower",
      "mvm",
      "pass",
      "pl",
      "plr",
      "pd",
      "sd"
    ],
    "res": [
      "4/3",
      "16/9"
    ],
    "position": [
      "center",
      "corners"
    ]
  }
}

=== GreySux/hud-db/hud-data/hypnotizehud.json
{
  "name": "HypnotizeHUD",
  "author": "Hypnotize",
  "social": {
    "steam_profile": "76561198058754493",
    "album": "https://imgur.com/a/4sgZ1"
  },
  "flags": [
    "fonts",
    "menus",
    "scoreboards",
    "crosshairs",
    "minmode",
    "streamer-mode",
    "materials",
    "customization"
  ],
  "traits": {
    "os": [
      "windows",
      "linux"
    ],
    "gamemode": [
      "tournament",
      "comp",
      "arena",
      "ad",
      "ctf",
      "cp",
      "halloween",
      "koth",
      "mannpower",
      "mvm",
      "pass",
      "pl",
      "plr",
      "pd",
      "rd",
      "sd",
      "tc"
    ],
    "res": [
      "4/3",
      "5/4",
      "16/9",
      "16/10"
    ],
    "position": [
      "center"
    ],
    "lang": [
      "en"
    ]
  },
  "repo": "https://github.com/Hypnootize/hypnotizehud",
  "hash": "8f61a79d3f03917c48b6a6904d59ea6ecdd8e3f1",
  "resources": [
    "hypnotizehud-banner",
    "hypnotizehud-menu",
    "hypnotizehud-backpack",
    "hypnotizehud-buff",
    "hypnotizehud-low",
    "hypnotizehud-minmode",
    "hypnotizehud-medic",
    "hypnotizehud-scoreboard",
    "hypnotizehud-spectator"
  ]
}

=== GreySux/hud-db/hud-data/supercomphud-omega.json
{
  "name": "SUPERCOMPHUD-OMEGA",
  "author": "lavaOnoes",
  "contributors": ["KACHOWHERO"],
  "flags": [
    "fonts",
    "menus",
    "scoreboards",
    "materials"
  ],
  "repo": "https://github.com/lavaOnoes/SUPERCOMPHUD-OMEGA",
  "hash": "89dc5548d68b4b5426799f0702878e8e9855044b",
  "prerelease": false,
  "resources": [
    "sketch-1700975276009",
    "1",
    "counter"
  ],
  "social": {
    "steam_profile": "76561198850021147",
    "youtube": "@lavaOnoes"
  },
  "traits": {
    "os": [
      "windows",
      "linux"
    ],
    "gamemode": [
      "tournament",
      "comp",
      "arena",
      "ad",
      "ctf",
      "cp",
      "halloween",
      "koth",
      "mannpower",
      "mvm",
      "pass",
      "pl",
      "plr"
    ],
    "res": [
      "4/3",
      "16/10",
      "16/9"
    ]
  }
}

=== GreySux/hud-db/hud-data/7hud.json
{
  "name": "7HUD",
  "author": "sevin",
  "verified": true,
  "social": {
    "steam_profile": "76561198056804798",
    "steam_group": "7HUD",
    "album": "https://imgur.com/a/yluqH"
  },
  "flags": [
    "fonts",
    "menus",
    "scoreboards",
    "crosshairs",
    "materials",
    "customization"
  ],
  "traits": {
    "os": [
      "windows",
      "mac",
      "linux"
    ],
    "gamemode": [
      "tournament",
      "comp",
      "arena",
      "ad",
      "ctf",
      "cp",
      "halloween",
      "koth",
      "mannpower",
      "mvm",
      "pass",
      "pl",
      "plr",
      "pd",
      "rd",
      "sd",
      "tc"
    ],
    "res": [
      "16/9"
    ]
  },
  "repo": "https://github.com/Sevin7/7hud",
  "hash": "a355383468c0f3dde0c764315a4cddc6a3b4ddd4",
  "resources": [
    "7hud-banner"
  ]
}

=== GreySux/hud-db/hud-data/thughud.json
{
  "name": "ThugHud",
  "author": "Russ",
  "contributors": [
    "N1te"
  ],
  "social": {
    "support": "https://steamcommunity.com/tradeoffer/new/?partner=413718379&token=3fJl5eiP",
    "issues": "https://discordapp.com/channels/@me/592276117822636033",
    "steam_profile": "76561198373984107",
    "steam_group": "TheEroticBarber",
    "discord": "russty._#0",
    "youtube": "@RusstyTF2",
    "twitch": "russ_tf2",
    "album": "https://imgur.com/a/08u3K00"
  },
  "traits": {
    "os": [
      "windows"
    ],
    "gamemode": [
      "tournament",
      "comp",
      "arena",
      "ad",
      "ctf",
      "cp",
      "halloween",
      "koth",
      "mannpower",
      "mvm",
      "pass",
      "pl",
      "plr",
      "pd",
      "rd",
      "sd",
      "tc"
    ],
    "res": [
      "4/3",
      "16/10",
      "16/9"
    ],
    "position": [
      "center"
    ]
  },
  "repo": "https://github.com/RussTIB/thughud",
  "hash": "90374efd3fa3c6c9717aec48f5dd4882d14ab903",
  "resources": [
    "ThugHud-pic",
    "ThugHud-banner"
  ]
}

=== GreySux/hud-db/hud-data/shrekhud.json
{
  "name": "ShrekHUD",
  "author": "Hypnotize",
  "social": {
    "steam_profile": "76561198058754493",
    "album": "https://imgur.com/a/i3TpBPa"
  },
  "flags": [
    "fonts",
    "menus",
    "scoreboards",
    "crosshairs",
    "materials"
  ],
  "traits": {
    "os": [
      "windows"
    ],
    "gamemode": [
      "tournament",
      "comp",
      "arena",
      "ad",
      "ctf",
      "cp",
      "halloween",
      "koth",
      "mannpower",
      "mvm",
      "pass",
      "pl",
      "plr",
      "pd",
      "rd",
      "sd",
      "tc"
    ],
    "res": [
      "4/3",
      "5/4",
      "16/9",
      "16/10"
    ]
  },
  "repo": "https://github.com/Hypnootize/ShrekHUD",
  "hash": "3c89fc0b4b2287dfebfa2e89eb573578cd3dd15d",
  "resources": [
    "shrekhud-banner",
    "shrekhud-mm",
    "shrekhud-loadout",
    "shrekhud-backpack",
    "shrekhud-buff",
    "shrekhud-hurt",
    "shrekhud-uber",
    "shrekhud-scoreboard"
  ]
}

=== GreySux/hud-db/hud-data/hud-fixes.json
{
  "name": "Community HUD Fixes",
  "author": "CriticalFlaw",
  "verified": true,
  "social": {
    "steam_profile": "76561198041892999",
    "twitter": "CriticalFlaw_",
    "discord": "hTdtK9vBhE"
  },
  "flags": [
    "customization",
    "crosshairs",
    "minmode",
    "materials"
  ],
  "traits": {
    "os": [
      "windows",
      "mac",
      "linux"
    ],
    "gamemode": [
      "tournament",
      "comp",
      "arena",
      "ad",
      "ctf",
      "cp",
      "halloween",
      "koth",
      "mannpower",
      "mvm",
      "pass",
      "pl",
      "plr",
      "pd",
      "rd",
      "sd",
      "tc"
    ],
    "res": [
      "4/3",
      "16/9",
      "16/10"
    ]
  },
  "repo": "https://github.com/CriticalFlaw/TF2HUD.Fixes",
  "hash": "eabd28aa5d2436b45eb78f0bf61b33a96c018db3",
  "resources": [
    "banner"
  ]
}
